### PR TITLE
Miklasr/5 screen reading and text to speech

### LINKED ISSUE #5: Screen reading/text to speech
Have an initial text to speech system working in the app. This can work by just reading out dummy text at this point.

### PR DESCRIPTION
**Pull request by miklasr**
# Details

- Investigate text to speech options
- Adds a demo image with an `accessibilityLabel` to demonstrate reading out text for an image/button/etc.
  - Tapping on the image when screen reader is on, triggers the accessibility message
- Adds a button that, when tapped, triggers the phone to speak some custom text with the current time
  - Demonstrates the ability to speak text on the fly, i.e., not hard-coded

# Screenshots/Gif (if appropriate)

text-to-speech

# Checklist

## Code
- [ ] ~I have added some tests~
- [ ] ~I have run the tests locally to ensure they all pass~
- [x] I have manually tested the functionality

## Documentation
- [x] I have updated documentation appropriately (GitHub Pages)
- [x] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

## Accessibility
- [x] Tested Accessibility on **Android**
  - [x] Any added fields can be read aloud by the screen reader
- [x] Tested Accessibility on **iOS**
  - [x] Any added fields can be read aloud by the screen reader

Closes Issue #5

### CODE REVIEW

**Review by Ashwin-MJ — CHANGES_REQUESTED** [review]
I tried this out using the iOS simulator and the accessibilityLabel for the image was not read out (it just skipped over it). I looked it up, and I think we might also need to set the `accessible` field to true:

```
    <Image
        accessible={true}
        source={require('../assets/images/icon.png')}
        style={{ width: 100, height: 100 }}
        accessibilityLabel="Accessible image"
     />
```

When I tested with this field added the "Accessible image" text was read out correctly. The button works great though!

**Comment by Ashwin-MJ** [comment]
On that note, do you think it's worth adding separate items in the checklist for testing screen reading on iOS and Android? We should try and support both equally as much as we can. I'm happy to do the tests on iOS for yourself and Conor

**Comment by miklasr** [comment]
I've made those changes.(Good suggestions, thanks)

**Comment by miklasr** [comment]
I have pushed the additions to documentation on coding style now

**Review by Ashwin-MJ — APPROVED** [review]
Looks good, I tested this on iOS so updated the PR checklist. Docs look good too!

**Pull request merged**
