### PR TITLE
Implement settings screen

### LINKED ISSUE #45: Settings screen
# Goal

Implement a settings screen which allows users to modify the colour theme of the application

# Plan

1. Create the settings screen
1. Figure out a way to modify colour themes
1. Come up with a few different themes to switch between

### PR DESCRIPTION
**Pull request by Ashwin-MJ**
# Details

- New settings screen which allows users to change the colour theme of the application
- Added some themes
- Ensure theme is retained when re-opening app

# Screenshots/GIF (if appropriate)
Check out the video below:
https://drive.google.com/file/d/1NIoYH8zpQWtxM6KGANDTWXUmBabz5jV4/view?usp=sharing

# Checklist

## Code
- [ ] I have added some tests
- [x] I have run the tests locally to ensure they all pass

## Documentation
- [ ] I have updated documentation appropriately (GitHub Pages)
- [ ] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

## Accessibility
- [x] Tested Accessibility on **Android**
  - [x] Any added fields can be read aloud by the screen reader
- [x] Tested Accessibility on **iOS**
  - [x] Any added fields can be read aloud by the screen reader

Closes #45

### CODE REVIEW

**Review by miklasr — CHANGES_REQUESTED** [review]
Really cool stuff!

Some minor requests from my end based on testing on my phone:
- Remove the ripple effect, because it causes a grey box to appear
- In settings "MONOCHROME" wraps over two lines
- In settings "HIGHCONTRAST" wraps over two lines and is a single word

For the last two, is it possible to resize text to the box?

**Review by C-Begley — DISMISSED** [review]
If we can get the top bar to also change, that'd be great, but happy to merge

**Comment by miklasr** [comment]
Looks really good; the text in the buttons now appears on a single line.

A major problem now is that it's quite slow to respond, taking about 40s from button tap to updating the screen. Whilst running for a few minutes this led to around 3000 frames being dropped.

**Comment by miklasr** [comment]
After re-installing it now works a lot smoother, so actually happy to merge

**Review by C-Begley — APPROVED** [review]

**Review by miklasr — APPROVED** [review]

**Pull request merged**
