### PR TITLE
Expansion pack beacon logic implemented

### LINKED ISSUE #50: Make HTTP requests to the database
# Goal

We will need to make asynchronous HTTP requests to the server to retrieve information for the expansion pack based on the UUID detected

# Plan

1. Create new file for http requests
1. Determine endpoint and structure of request to be made
1. Have an exported function which can be called elsewhere

### LINKED ISSUE #51: Logic to check version number and update database if required
# Goal

After making a request to the database, the version number of the expansion pack will be returned. We then need logic to check if this is newer than the existing pack on the phone (or if it doesn't even exist on the phone) and if so, download the expansion pack and update the database 

# Plan

1. Logic to lookup version number for given pack
1. Download file from endpoint
1. Update database

### LINKED ISSUE #52: Alert screen for when an expansion pack beacon is detected
# Goal

Need a new screen/popup when an expansion pack beacon is detected

# Plan

1. Decide how we want this to work
1. Implement front end solution
1. Ensure it works for a beacon with the required beacon name indicating it is an expansion pack beacon

### PR DESCRIPTION
**Pull request by Ashwin-MJ**
# Details

- Can now differentiate between an expansion pack beacon and a normal beacon
- If an expansion pack beacon is detected, check Firebase to see if a new pack is available for this location (using version number). If a new pack is available **or** if the pack does not exist on the user's device (e.g. it is their first time passing that location) then a second request is made to fetch the contents of the expansion pack and then put it into the local database
- The following workflow now works:
   - Walk past expansion pack beacon which has been added to the Firebase and has a corresponding expansion pack file added to the other GitHub repo [here](https://github.com/ESE-Peasy/NarrateMyWay-expansion-packs)
   - If the expansion pack relating to this beacon has not been downloaded before, or if it is out of date, the system will automatically download the latest expansion pack into local storage
   - When you walk past a beacon included in the expansion pack, the enriched content is provided to the user

# Screenshots/GIF (if appropriate)

https://gla.sharepoint.com/sites/A2CM/Shared%20Documents/DST5/Videos/nmw-expansion-pack.mp4

- At 00:07 the beacon is detected with its NMW code (no enriched content available)
- Sometime between 00:20 and 00:55 an expansion pack beacon is detected which includes enriched content for the previous beacon
- At 00:57, the beacon is detected again but this time with the enriched content since it has been downloaded

# Checklist

## Code
- [x] I have run the tests locally to ensure they all pass

## Documentation
- N/A

## Accessibility
No actual front end changes were made here

Closes #50, #51 #52

### CODE REVIEW

**Review by miklasr — DISMISSED** [review]
Really nice changes. I won't be able to test it on my end, but I've had a look at the video. Looking through the code I don't see any issues and everything looks very cleanly written. Regarding what you mentioned earlier, I agree that it makes sense to put those new functions into the lookup.tsx file.

Really nice stuff, it's cool to see all the parts of the project coming together like this!

**Review by C-Begley — DISMISSED** [review]
LTGM

**Review by C-Begley — APPROVED** [review]
LGTM

**Pull request merged**
