### PR TITLE
Bluetooth disabled alert

### LINKED ISSUE #62: Alert if Bluetooth is disabled
# Goal

An alert should be presented to the user if Bluetooth is disabled for the device as the app will not function

# Plan

1. Use the ble-plx library to set a listener for when the Bluetooth state changes and display an alert accordingly

### PR DESCRIPTION
**Pull request by Ashwin-MJ**
# Details

- An alert is now displayed in Bluetooth is disabled
- On Android there is an option to enable Bluetooth via this alert, however this is not possible on iOS

# Screenshots/GIF (if appropriate)

# Checklist

## Code
- [ ] I have added some tests
- [x] I have run the tests locally to ensure they all pass

## Documentation
N/A

## Accessibility
- [x] Tested Accessibility on **Android**
  - [x] Any added fields can be read aloud by the screen reader
- [x] Tested Accessibility on **iOS**
  - [x] Any added fields can be read aloud by the screen reader

Closes #62

### CODE REVIEW

**Review by miklasr — DISMISSED** [review]
Nice addition. It pops up when starting without Bluetooth and enables without going to settings on Android, so very smooth.

Location permissions aren't enabled with this, but they are needed. Could we add that in this PR, or should we do that in another?

**Review by Andrew-Ritchie — DISMISSED** [review]
Works really well for me, good job! :)

**Comment by C-Begley** [comment]
It seems if I disable both, it only alerts for one

Edit: It seems bluetooth warning only happens on start up, where as location will remind any time I turn it off

**Comment by miklasr** [comment]
Bug: I start the app with no permissions. I am prompted visually and audibly for both Bluetooth and location. In one particular situation the location request box took precedence over Bluetooth. I tapped the enable button and the subsequent confirm button. Location permissions were then enabled. Bluetooth was not enabled, but there was no warning/error to that effect.

It looks like enabling location disarmed both Bluetooth and location warnings, when it should only have disarmed the location warning.

**Review by Andrew-Ritchie — APPROVED** [review]
Working well for me now! :)

**Review by miklasr — APPROVED** [review]

**Comment by C-Begley** [comment]
Works for me

**Review by C-Begley — APPROVED** [review]

**Pull request merged**
