### PR TITLE
Update docs for linux env install

### PR DESCRIPTION
**Pull request by miklasr**
# Details

- Add instructions for installing Node on Linux

# Checklist

## Code
- [ ] ~I have added some tests~
- [ ] ~I have run the tests locally to ensure they all pass~

## Documentation
- [x] I have updated documentation appropriately (GitHub Pages)
- [x] I have tested the updated GitHub Pages locally to ensure the changes to documentation render correctly (see this [Guidance](https://ese-peasy.github.io/PosturePerfection/guidance.html) page)

Closes Issue #

### CODE REVIEW

**Comment by miklasr** [comment]
Should I add _sites to the .gitignore?

**Comment by Ashwin-MJ** [comment]
> Should I add _sites to the .gitignore?

Yeah I think we should. Do you mind doing that and updating the PR?

**Comment by miklasr** [comment]
> > Should I add _sites to the .gitignore?
> 
> Yeah I think we should. Do you mind doing that and updating the PR?

Cool, that's done. Shall I merge?

**Review by Ashwin-MJ — APPROVED** [review]
Looks good!

**Pull request merged**
